### ISSUE TITLE
Interactive Juypyter Notebook figures dont work on Windows

### ISSUE THREAD

**Issue by merrygoat** [MechMicroMan/DefDAP#16]
The tk graphics back end doesn't seem to work on Windows in the Jupyter notebook. For me on Win 10 the "nbAgg" backend works well however, this can be enabled with the command: `%matplotlib notebook`

**Comment by tom-armitage** [comment]
I have managed to get interactive figures working in windows using %matplotlib ipympl (instead of widget). The installation steps are as below:

14

Complete steps
Install nodejs, e.g. conda install nodejs.
Install ipympl, e.g. pip install ipympl.
[Optional, but recommended; update JupyterLab, e.g.
pip install --upgrade jupyterlab.]
[Optional, but recommended; for a local user installation, run:
export JUPYTERLAB_DIR="$HOME/.local/share/jupyter/lab".]
Install extensions:

jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib
Enable widgets: jupyter nbextension enable --py widgetsnbextension.

Restart JupyterLab.
Decorate with %matplotlib widget (I had to use %matplotlib IPYMPL)

Source: https://stackoverflow.com/questions/50149562/jupyterlab-interactive-plot
