### ISSUE TITLE
Error in plotRDR

### ISSUE THREAD

**Issue by eugenianietov** [MechMicroMan/DefDAP#94]
Hi everyone,

I am using the GrainInspector to analyze the slip traces observed in some sample Ni superalloy HRDIC maps provided by the authors in Zenodo. I am trying to use the RDR calculation after hitting the "Run RDR only on group 0" button, but I am getting an error stating that "AttributeError: 'Map' object has no attribute 'slipSystems'". I have tried to add the slipSystems variable to the Phase object as static, but then I got the same error on line 540 of the inspector.py script.

Any clue of what can be wrong? I can provide screenshots of my errors if necessary.

Thanks a lot in advance!!

Eugenia

**Comment by rhysgt** [comment]
Hi Eugenia,

What version of DefDAP are you using and from which branch (master or develop)?

In the first instance, could try the version in the develop branch instead which has some bug fixes which might solve the problem.

In newer versions of defdap, the slipSystems are automatically determined based on the crystal structure of the phase, so that attribute should be automatically populated.

**Comment by eugenianietov** [comment]
Hi Rhys,

The development branch worked perfectly; using it never came to my mind! Thanks a lot!!

Eugenia
